### ISSUE TITLE
想实现CQRS，如何列表查询？

### ISSUE THREAD

**Issue by tky753** [newbe36524/Newbe.Claptrap#60]
列表查询，肯定是在状态表查询了。
但是，看生成的`claptrap_states`中数据(state_data字段)，都压缩成一个json字符串了，感觉这张表就是个**snapshot**，不是用来列表查询的，想要实现列表查询，是不是还要再自己维护一张**数据状态表**？
或者有没有办法自定义`claptrap_states`，让具体数据不挤在一个字段里？

**Comment by newbe36524** [comment]
我认为你想知道的，其实是物化视图。若想要实现物化视图，可以通过 minion 写入到另外的数据表中。这也是 event sourcing 中的一种做法。请参见 https://docs.microsoft.com/en-us/azure/architecture/patterns/event-sourcing#solution 中 materialized views 的做法

**Comment by tky753** [comment]
就是觉得，已经有一张`claptrap_states`了，又要自己写一张**数据状态表**，是不是冗余了？
如果`claptrap_states`是`claptrap_snapshot`那就可以理解了

**Comment by newbe36524** [comment]
从逻辑上说，物化视图和状态存储是独立的内容。因此建立分开存储。而且就目前而言，claptrap_states 确实是 claptrap_snapshot。仅仅是为了加快时间还原状态的速度而存在。
从实现上来说，为了兼容考虑状态存储的灵活性（替换序列化方式（二进制、jsonb），存储中间件选型），因此，这部分若要实现你要的效果，建议自定义。

**Comment by tky753** [comment]
状态存储，没了解过不敢乱说。想问一下，看现在的实现，每次更新一个字段，是不是就要update整个`state_data`？
那样的话，如果`state_data`中的数据结构有几百个字段，是不是不太合理？

**Comment by newbe36524** [comment]
是的，而且这从设计上是无法解决的问题。

但这个问题其实可以分为两个部分：

1. 物化视图，正对业务的自定义视图

状态是被当做一个整体进行管理的。整体更新和修订有助于在这个小的领域内保持逻辑的简单。如果希望能够单独的更新字段或者维护特有的数据，物化视图才是建议的做法。

2. 超大结构或者复杂结构

tate_data 是 schema free 的结构，通常稍微复杂一点的结构都无法直接映射到关系型数据库，例如树形、大列表等等。
其实，在未来，state_data 也将追加一个特性。也就是自定义上面这种映射关系。比如，对于超大 List (万条记录)。这个时候可以考虑将这种数据以行记录的形式保存，而不是整体序列化。而这种具体的映射关系，框架本身也还是不会考虑如何映射，仅仅能够给出自定映射的接口即可。
