### ISSUE TITLE
StorageOptions中的DatabaseName和ConnectionName只在Strategy为Known的时候生效

### ISSUE THREAD

**Issue by tky753** [newbe36524/Newbe.Claptrap#61]
**StorageOptions**中的**DatabaseName**和**ConnectionName**只在**Strategy**为**Known**的时候生效，
其他时候，都是 默认值**claptrap**，以mongodb的设置为例，是不是设置为 
```C#
{
  DatabaseName = storageOptions.SchemaName ?? Defaults.SchemaName,
  ConnectionName = storageOptions.ConnectionName ?? Defaults.ConnectionName
}
```
比较合理?
否则想要自定义表来存储事件和状态，就只能设置为**Known**了

**Comment by newbe36524** [comment]
我想本意应该是在这种时候可以选择使用以下重载来自定义所有的细节：
https://github.com/newbe36524/Newbe.Claptrap/blob/97e1b7ea140866f165d5d3192f446a1be185f34c/src/Newbe.Claptrap.StorageProvider.MongoDB/Extensions/MongoDBEvenStoreConfigurator.cs#L59

StorageOptions 并不存在 DatabaseName 和 ConnectionName 。只有 IMongoDBEventStoreLocator 。因此，此时只能通过传入 locator 来自定义存储位置
