### ISSUE TITLE
StorageProvider是否封装的太死了

### ISSUE THREAD

**Issue by tky753** [newbe36524/Newbe.Claptrap#62]
比如，我想用MongoDB来存储，想要记录查询的命令行，需要这样来初始化`MongoClient`:
```C#
var mongoConnectionUrl = new MongoUrl(connectionString);
var mongoClientSettings = MongoClientSettings.FromUrl(mongoConnectionUrl);
mongoClientSettings.ClusterConfigurator = cb => {
    cb.Subscribe<CommandStartedEvent>(e => {
        logger.Log($"{e.CommandName} - {e.Command.ToJson()}");
    });
};
var mongoCfgClient = new MongoClient(mongoClientSettings);
```
用`Newbe.Claptrap.StorageProvider.MongoDB`，就很难实现这种扩展。
感觉，不用反射，改用依赖注入，像EfCore那样， 扩展个`UseXXXDb((options) => { ... })`方法，能更好的榨干Driver的功能。

**Comment by newbe36524** [comment]
我觉得你的提议非常不错。
目前看来可以通过实现并注入一个新的 DbFactory 来实现你想要的效果。
https://github.com/newbe36524/Newbe.Claptrap/blob/master/src/Newbe.Claptrap.StorageProvider.MongoDB/DbFactory.cs#L5
我认为，可以结合你说的方式，修改上面这个类。使得其可以接收 StartUp 中传入的 options 来实现自定义。
